import type { Metadata } from 'next';
import {
  ModalProvider,
  ToastContainer,
  ToastProvider,
} from '@/shared/ui/feedback';
import GlobalNavigationBar from '@/shared/ui/navigation/global-navigation-bar/global-navigation-bar';
import AuthProvider from '@/feature/auth/provider/auth-provider';
import ReactQueryClientProvider from '@/provider/QueryProvider';
import '../shared/ui/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <AuthProvider>
        <ModalProvider>
          <ToastProvider>
            <link
              rel='preconnect'
              href='https://vbdbvqzfphlwkizvsjkx.supabase.co'
              crossOrigin=''
            />
            <html lang='ko'>
              {/* <ReactScan /> */}
              <body className='bg-secondary relative flex h-dvh flex-col antialiased'>
                <div id='modal' />
                <GlobalNavigationBar />
                <main className='m-auto h-full w-full max-w-[1024px] flex-1'>
                  {children}
                </main>
                <ToastContainer />
              </body>
            </html>
          </ToastProvider>
        </ModalProvider>
      </AuthProvider>
    </ReactQueryClientProvider>
  );
}
