import type { Metadata } from 'next';
import ReactQueryClientProvider from '@/provider/QueryProvider';
import '../shared/ui/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang='en'>
        <body className='antialiased'>{children}</body>
      </html>
    </ReactQueryClientProvider>
  );
}
