import type { Metadata } from 'next';
import { ModalProvider } from '@/shared/ui/feedback/modal/modal-provider';
import GlobalNavigationBar from '@/shared/ui/navigation/global-navigation-bar/global-navigation-bar';
import ReactQueryClientProvider from '@/provider/QueryProvider';
import '../shared/ui/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <ModalProvider>
        <html lang='en'>
          <body className='bg-secondary flex h-screen flex-col antialiased'>
            <div id='modal' />
            <GlobalNavigationBar isLoggedIn={false} />
            <main className='m-auto w-full max-w-[1024px] flex-1'>
              {children}
            </main>
          </body>
        </html>
      </ModalProvider>
    </ReactQueryClientProvider>
  );
}
