export const ICON_NAMES = [
  'alert-circle',
  'at-sign',
  'calendar',
  'check-circle',
  'check',
  'chevron-down',
  'chevron-up',
  'copy',
  'corner-down-right',
  'earth',
  'edit-2',
  'edit',
  'grip-vertical',
  'heart',
  'help-circle',
  'google-login',
  'image-plus',
  'image',
  'kakao-logo',
  'line-logo',
  'link',
  'lock',
  'log-in',
  'log-out',
  'logo',
  'menu',
  'message-circle',
  'message-heart',
  'message-loading',
  'minus',
  'plus',
  'refresh-ccw',
  'send',
  'smile-move',
  'smile',
  'trash',
  'kakao-login',
  'naver-login',
  'x',
  'user',
] as const;

export const ICON_SIZES = [12, 16, 24, 32, 36, 40, 48] as const;
